Fix terraform

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -50,17 +50,14 @@ jobs:
       - name: Move zip code to upload folder
         run: mv code.zip terraform/aws
       
+      - name: Cd into terraform folder
+        run: cd terraform/aws
+      
       - name: Download tf state
-        run: echo -e 'aws s3 cp s3://products-watcher-data/dev/terraform.tfstate terraform.tfstate \nif [ $? -eq 0 ]; then \necho "File exists" \nelse \necho "File does not exist"\nfi' > terraform_pre_init.sh
-      - run: sh terraform_pre_init.sh
-      - run: rm terraform_pre_init.sh
-      - run: aws s3 cp s3://products-watcher-data/dev/terraform.tfstate terraform.tfstate || echo "Failed"
+        run: aws s3 cp s3://products-watcher-data/dev/terraform.tfstate terraform.tfstate || echo "Failed"
         
       - name: Terraform Init
         run: terraform init
-
-      - name: Show directory
-        run: ls
 
       - name: Terraform Plan
         run: terraform plan
